### ISSUE TITLE
file picker fails

### ISSUE THREAD

**Issue by nissaba** [jkdhn/mcumgr-dart#7]
After connecting to the Ble device and opening the file chooser and selecting the firmware file it fail to get the file white this log in the console.  

[DocumentManager] The view service did terminate with error: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Terminated=disconnect method}
[DocumentManager] Failed to associate thumbnails for picked URL file:///private/var/mobile/Containers/Shared/AppGroup/4DFB19F8-04CD-4113-9E7C-CA84472D0FDB/File%20Provider%20Storage/fv1.1.zip with the Inbox copy file:///private/var/mobile/Containers/Data/Application/646BAEBB-F4ED-4B0C-873C-E1B865368A15/tmp/com.argon18.flutter.smp.example-Inbox/fv1.1.zip: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x280da09c0 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: incorrect magic
#0      new McuImageHeader.decode (package:mcumgr/img.dart:404:7)
#1      new McuImage.decode (package:mcumgr/img.dart:500:35)
#2      _DeviceScreenState._update (package:mcumgr_example/device.dart:155:28)
<asynchronous suspension>

**Comment by nissaba** [comment]
Closing. the firmware I was provided for testing was wrong.
